# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'nfbox' do

  # Pods for nfbox
  pod 'Alamofire', '~> 4.0'
  pod 'Kingfisher', '~> 3.0'
  pod 'SwiftyJSON'
  pod 'NMPopUpViewSwift'
  

end
